Задача 1 выполнена
martyushevleoned/CurrencyBot pull request #8
Opened 2024-05-05 19:13 UTC by martyushevleoned

2024-05-08 20:38 UTC, vpyzhyanov requested changes
В целом очень даже хорошо сделали, молодцы, мне понравилось. Но замечания, конечно же, есть.

Нарушили требования к проекту, использовали static.

Нет тестов на основную функциональность, например на класс `UpdateController`

Снижаю один балл за гит за неуважение к код ревьюеру:

![image](https://github.com/martyushevleoned/CurrencyBot/assets/71599019/916bd888-ea38-4b79-8ba5-bbddea945191)

Молодцы, что пользуетесь пулл реквестами

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
дублирование свойств. Они уже определены в родительском проекте

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
ещё одно дублирование

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/pom.xml
> +            <version>1.0-SNAPSHOT</version>
версии тут быть не должно. Определите в dependencyManagment в родительском модуле. Там можно использовать в качестве версии `${project.version}`

2024-05-08 20:38 UTC, vpyzhyanov commented on pom.xml
> +                <version>2.23.1</version>
почему-то одна версия выделяется

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +    public TelegramBot(BotConfig botConfig, UpdateController updateController) {
тут варнинг о том, что конструктор без параметров deprecated, надо решить проблему

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +    public String getBotToken() {
метод deprecated

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +    public TelegramBot(BotConfig botConfig, UpdateController updateController) {
Спринг своей автоматикой расслабляет нас, но не надо поддаваться. Лучше явно писать на конструкторе `@Inject` или `@Autowired`, чтобы явно показать, что параметры - это бины

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/config/BotInitializer.java
> +        telegramBotsApi.registerBot(bot);
Телеграмм бот сам может себя зарегистрировать, вовсе не обязательно создавать целый инициализатор для этого

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/config/BotInitializer.java
> +public class BotInitializer {
лишний класс

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +        updateController.registerTelegramBot(this);
обнаружена циклическая зависимость!

1. Хитрое решение, но слишком много кода и есть сеттер, который нарушает инкапсуляцию. Достаточно было в updateController прописать зависимость и пометить её аннотацией `@Lazy`
2. Либо можно каждый раз передавать бота в метод processUpdate. А лучше не бота, а интерфейс, который умеет только отправлять сообщения (только необходимый функционал)

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                            ApiMenu apiMenu) {
Добро пожаловать на тёмную сторону ООП, слишком много параметров. Но, о чудо, оказывается спринг дружит с полиморфизмом :-) и можно писать так:

```java
    @Autowired
    public UpdateController(List<Menu> menus) {
        this.menus = menus;
    }
```

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +            if (menu instanceof SendMenu sendMenu) {
ой, не надо лишних операций. Если у вас есть несколько видов меню, то сделайте несколько списков с этими элементами. Не надо скидывать всё в одну кучу.

```java
List<SendMenu> sendMenus;
List<CallbackMenu> callbackMenus;
```

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                if (sendMenu.matchSendMessage(message)) {
не надо писать несколько if подряд, это увеличивает вложенность. Большая вложенность - это плохо. Такие ифы легко объединяются через условие `&&`

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                        LOG.error(e.getMessage());
всегда пишите человекочитаемое сообщение об ошибке. И исходное исключение тоже надо обязательно передать, это поможет для разбора ошибок.

`LOG.error("человеческое сообщение", e);`

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                if (sendMenu.matchSendMessage(message)) {
перебирать все меню просто для того, чтобы сопоставить команду по equals - не очень эффективно. Лучше бы построили `Map<название команды, Menu>` и вызывали сразу нужный

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                if (callbackMenu.matchEditMessage(callbackQuery)) {
методы, которые возвращают логическое значение обязаны начинаться с вопросительного глагола, например is, has и др. В данном случае будет `isMatchedCallbackQuery`

P.S. при чём тут `EditMessage` - вообще непонятно

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/menu/menus/MainMenu.java
> +package ru.urfu.controller.menu.menus;
в именах пакетов не принято использовать множественное число. Пакет - это директория, понятное дело она может иметь несколько файлов внутри

Не надо 2 раза писать слово menu, хватит одного

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/menu/menus/MainMenu.java
> +    private static final String TRACKED_CURRENCIES_MENU_BUTTON_TEXT = MenuTypes.TRACKED_CURRENCY_LIST.getText();
не надо посредников. Не надо копировать константы. Используйте сразу оригинал.

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/menu/menus/apiMenu/ApiListMenu.java
> +    private static final String API_NAME_FLAG = Flags.API_NAME_FLAG.getName();
похоже во всех командах бессмысленное копирование

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/service/ApiService.java
> +        return apiManager.getPossibleRequests();
вот оно как, получается - этот класс бездельник, он сам ничего не делает, а всю работу делегирует apiManager. Выбросить его немедленно! ) Выбирайте, либо существует ApiService, либо ApiManager

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +            currencyApiList.forEach(currencyApi ->
Никаких статических блоков!

```java
currencyApiMap = currencyApiList.stream()
                        .collect(Collectors.toUnmodifiableMap(CurrencyApi::getName, Function.identity()));
```

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +            currencyApiList.forEach(currencyApi ->
тут тоже

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +            throw new ApiNotFoundException("Указанный API не существует");
если кидаете исключение, то будьте добры в JavaDoc его описать и написать в каком случае оно возникает

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/service/TrackService.java
> +        return trackedCurrencies.getOrDefault(chatId, Set.of()).stream().toList();
зачем преобразовывать в список?

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/model/CurrencyRequest.java
> +public class CurrencyRequest {
можно легко преобразовать в record

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/model/ApiDescription.java
> +    public String toString() {
toString() нельзя использовать ни для чего, кроме отладки кода. Создайте свой метод

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +        return currencyApi.getPrice(currencyRequest.getCurrency());
2 раз вызывается получение валюты. В переменную её

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/api/CbrApi.java
> +    private static final ApiDescription DESCRIPTION = new ApiDescription(NAME, "https://www.cbr-xml-daily.ru/", "1 день");
static запрещён!!!

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/api/CbrApi.java
> +        put("Евро", "rates.EUR");
1. Никаких статических блоков!
2. Используйте Map.of(). У вас всего 4 значения. Получится как раз неизменяемая коллекция

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/api/CbrApi.java
> +    private final CurrencyCache cache = new CurrencyCache(updateDuration);
`updateDuration` не меняется абсолютно нигде, поэтому можно сделать inline.

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/utils/CurrencyCache.java
> +        return new Date().getTime() - currencyResponseMap.get(currencyName).getDatetime().getTime() < updateTime;
Используйте более современные и удобные классы, чем long и Date:

```java
        return Duration.between(currencyResponseMap.get(currencyName).getDatetime(), Instant.now())
                .minus(updateTime).isNegative();
```

Соответственно `getDatetime()` должен возвращать `Instant`

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/utils/JsonParser.java
> +                    throw new ParseJsonException("Недостижимый путь в json");
Исключение должно быть описано

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/utils/JsonParser.java
> +                : object.toString();
`Objects.toString(object)`

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/utils/JsonParser.java
> +                int index = Integer.parseInt(key);
2 раза парсится одна и та же строка

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/main/java/ru/urfu/utils/RequestSender.java
> +            throw new RuntimeException(e);
должно быть человекочитаемое сообщение

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/test/java/ru/urfu/ApiManagerTest.java
> +        Assert.assertEquals(Set.of(apiName), apiManager.getAllApiNames());
очень похоже на тестирование mock

2024-05-08 20:38 UTC, vpyzhyanov commented on currency-api/src/test/java/ru/urfu/utils/CurrencyCacheTest.java
> +        cache = new CurrencyCache(Duration.ofSeconds(1));
слишком долго, лучше сделать 100 мс

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/test/java/ru/urfu/service/ApiServiceTest.java
> +        possibleRequests.forEach(currencyRequest -> {
стоит сервису вернуть пустой список и тест превратится в тыкву

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/test/java/ru/urfu/service/ApiServiceTest.java
> +            Assert.assertTrue(parts[1].startsWith("Оффициальный сайт: "));
Официальный пишется с одной буквой `ф`

2024-05-08 20:38 UTC, vpyzhyanov commented on telegram-bot/src/test/java/ru/urfu/service/ApiServiceTest.java
> +        apiNames.forEach(apiName -> {
стоит сервису вернуть пустой список и тест превратится в тыкву

2024-05-08 20:39 UTC, vpyzhyanov commented
А ещё ветка должна называться task1. И у каждого должна быть своя именная ветка, я таких не наблюдаю

2024-05-23 23:10 UTC, martyushevleoned commented on currency-api/pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
исправлено

2024-05-23 23:10 UTC, martyushevleoned commented on telegram-bot/pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
исправлено

2024-05-23 23:10 UTC, martyushevleoned commented on telegram-bot/pom.xml
> +            <version>1.0-SNAPSHOT</version>
исправлено

2024-05-23 23:10 UTC, martyushevleoned commented on pom.xml
> +                <version>2.23.1</version>
исправлено

2024-05-23 23:11 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +    public TelegramBot(BotConfig botConfig, UpdateController updateController) {
исправлено

2024-05-23 23:11 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +    public String getBotToken() {
исправлено

2024-05-23 23:11 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +    public TelegramBot(BotConfig botConfig, UpdateController updateController) {
исправлено

2024-05-23 23:11 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/config/BotInitializer.java
> +        telegramBotsApi.registerBot(bot);
исправлено

2024-05-23 23:11 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/config/BotInitializer.java
> +public class BotInitializer {
исправлено

2024-05-23 23:12 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/TelegramBot.java
> +        updateController.registerTelegramBot(this);
Исправил аннотацией Lazy

2024-05-23 23:13 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                            ApiMenu apiMenu) {
Исправил во всех местах, где можно так сделать

2024-05-23 23:14 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +            if (menu instanceof SendMenu sendMenu) {
исправлено

2024-05-23 23:14 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                if (sendMenu.matchSendMessage(message)) {
исправлено

2024-05-23 23:14 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                        LOG.error(e.getMessage());
исправлено

2024-05-23 23:15 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                if (sendMenu.matchSendMessage(message)) {
Оба интерфейса переработаны так, что листы получилось заменить на Map

2024-05-23 23:15 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +                if (callbackMenu.matchEditMessage(callbackQuery)) {
исправлено

2024-05-23 23:15 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/menu/menus/MainMenu.java
> +package ru.urfu.controller.menu.menus;
исправлено

2024-05-23 23:16 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/menu/menus/MainMenu.java
> +    private static final String TRACKED_CURRENCIES_MENU_BUTTON_TEXT = MenuTypes.TRACKED_CURRENCY_LIST.getText();
исправлено

2024-05-23 23:16 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/controller/menu/menus/apiMenu/ApiListMenu.java
> +    private static final String API_NAME_FLAG = Flags.API_NAME_FLAG.getName();
исправлено

2024-05-23 23:16 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/service/ApiService.java
> +        return apiManager.getPossibleRequests();
Оставлен один класс из модуля currency-api

2024-05-23 23:16 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +            currencyApiList.forEach(currencyApi ->
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +            currencyApiList.forEach(currencyApi ->
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +            throw new ApiNotFoundException("Указанный API не существует");
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on telegram-bot/src/main/java/ru/urfu/service/TrackService.java
> +        return trackedCurrencies.getOrDefault(chatId, Set.of()).stream().toList();
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/model/CurrencyRequest.java
> +public class CurrencyRequest {
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/model/ApiDescription.java
> +    public String toString() {
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/ApiManager.java
> +        return currencyApi.getPrice(currencyRequest.getCurrency());
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/api/CbrApi.java
> +    private static final ApiDescription DESCRIPTION = new ApiDescription(NAME, "https://www.cbr-xml-daily.ru/", "1 день");
исправлено

2024-05-23 23:17 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/api/CbrApi.java
> +        put("Евро", "rates.EUR");
исправлено

2024-05-23 23:18 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/api/CbrApi.java
> +    private final CurrencyCache cache = new CurrencyCache(updateDuration);
исправлено

2024-05-23 23:18 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/utils/CurrencyCache.java
> +        return new Date().getTime() - currencyResponseMap.get(currencyName).getDatetime().getTime() < updateTime;
исправлено

2024-05-23 23:18 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/utils/JsonParser.java
> +                    throw new ParseJsonException("Недостижимый путь в json");
исправлено

2024-05-23 23:18 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/utils/JsonParser.java
> +                : object.toString();
исправлено

2024-05-23 23:19 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/utils/JsonParser.java
> +                int index = Integer.parseInt(key);
Библиотека для парсинга json заменена на новую, в которой уже есть функционал получения значения по пути

2024-05-23 23:19 UTC, martyushevleoned commented on currency-api/src/main/java/ru/urfu/utils/RequestSender.java
> +            throw new RuntimeException(e);
исправлено

2024-05-23 23:20 UTC, martyushevleoned commented on currency-api/src/test/java/ru/urfu/ApiManagerTest.java
> +        Assert.assertEquals(Set.of(apiName), apiManager.getAllApiNames());
исправлено

2024-05-23 23:20 UTC, martyushevleoned commented on currency-api/src/test/java/ru/urfu/utils/CurrencyCacheTest.java
> +        cache = new CurrencyCache(Duration.ofSeconds(1));
исправлено

2024-05-23 23:20 UTC, martyushevleoned commented on telegram-bot/src/test/java/ru/urfu/service/ApiServiceTest.java
> +        possibleRequests.forEach(currencyRequest -> {
исправлено

2024-05-23 23:20 UTC, martyushevleoned commented on telegram-bot/src/test/java/ru/urfu/service/ApiServiceTest.java
> +            Assert.assertTrue(parts[1].startsWith("Оффициальный сайт: "));
исправлено

2024-05-23 23:20 UTC, martyushevleoned commented on telegram-bot/src/test/java/ru/urfu/service/ApiServiceTest.java
> +        apiNames.forEach(apiName -> {
исправлено

2024-06-06 04:09 UTC, vpyzhyanov commented
По нашей договорённости исправлять замечания должен был Максим Новожилов

2024-06-06 04:30 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/UpdateController.java
> +        commandMenuMap = commandMenus.stream().collect(Collectors.toUnmodifiableMap(commandMenu -> commandMenu.getUserCommand().getCommand(), Function.identity()));
слишком длинная строчка, это тяжело читать. Более 120 символов это уже слишком много. Я предпочитаются ориентироваться на 90 символов

2024-06-06 04:30 UTC, vpyzhyanov commented on telegram-bot/src/main/java/ru/urfu/controller/menu/menus/MainMenu.java
> +package ru.urfu.controller.menu.menus;
я просил не писать несколько раз одно и то же слово в именах пакетов.

![image](https://github.com/martyushevleoned/CurrencyBot/assets/71599019/fbd8bb34-fea6-4136-9cae-1c1f8aef6b4b)

Если мы находимся в пакете menu, это означает, что все дочерние пакеты тоже относятся к меню. (А в именах классов писать надо, так что для классов всё в порядке)

2024-06-06 04:40 UTC, vpyzhyanov approved these changes
Задача принята

2024-06-15 04:05 UTC, merged